# Generated by Django 5.1.7 on 2025-03-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
    ]
