# Generated by Django 5.1.7 on 2025-03-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('passport', models.CharField(max_length=50, verbose_name='Passport')),
                ('rnm', models.CharField(max_length=50, verbose_name='RNM')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('etat', models.CharField(max_length=100, verbose_name='État')),
                ('contact', models.CharField(max_length=20, verbose_name='Contact')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('etudiant', models.CharField(choices=[('sim', 'Oui'), ('nao', 'Non')], max_length=3, verbose_name='Vous êtes étudiant ?')),
                ('cours', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cours')),
                ('etablissement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Établissement')),
                ('profession', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profession')),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
            },
        ),
    ]
