# Generated by Django 5.1.7 on 2025-03-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_usuariochat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioChat',
        ),
    ]
