"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import os





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y%ai6#1tp&a^$d=m^*k-*x(1^12$2*(8*ce)fquo_u3k)!zmpx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.onrender.com']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_home',
    'app_noticias',
    'app_atividade',
    'cadastro',

]

ASGI_APPLICATION = 'setup.asgi.application'




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'
# settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Deixe vazio ou adicione caminhos personalizados, se necessário
        'APP_DIRS': True,  # Isso permite que o Django procure templates dentro dos apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'





# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Embaixada_GA',
        'USER': 'Admin01',
        'PASSWORD': 'gabon241',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Diretório onde os arquivos estáticos serão coletados
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / "static"]  # Caminho para a pasta static

# Configuração de uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

LOGIN_REDIRECT_URL = "chat-page"


LOGOUT_REDIRECT_URL =  "login-user"




# Configuração do logo
SIMPLEUI_LOGO = '/static/images/Design sans titre (4).png'

# Configurações da página de login
SIMPLEUI_HOME_INFO = False  # Remove os cards da página inicial do admin
SIMPLEUI_LOGIN_SHOW_FORM = True  # Exibir o formulário no login
SIMPLEUI_LOGIN_SHOW_HELP = False  # Oculta a ajuda padrão no login
SIMPLEUI_LOGIN_SHOW_COPYRIGHT = False  # Remove o rodapé padrão
SIMPLEUI_LOGIN_SHOW_POWERED_BY = False  # Remove "Powered by SimpleUI"


# Configuração do menu
SIMPLEUI_CONFIG = {
    'menu_display': [
        'App_Noticias',
        'Comentarios',
        'Comunicados',
        'Eventos',
        'Noticias',
        'Autenticação e Autorização',
        'Cadastro',
        'Cadastros',
        'Meu modelos',
        'App_Atividade',
        {
            'name': 'Cadastro',  
            'icon': 'fas fa-address-card',
            'models': [
                {
                    'name': 'Cadastros',
                    'icon': 'fas fa-list',
                    'models': [
                        {'name': 'Modelo_1', 'icon': 'fas fa-user'},
                        {'name': 'Modelo_2', 'icon': 'fas fa-users'}
                    ]
                }
            ]
        }
    ],
}

# Configuração dos ícones
SIMPLEUI_ICON = {
    'App_Noticias': 'fas fa-newspaper',
    'Comentarios': 'fas fa-comments',
    'Comunicados': 'fas fa-bullhorn',
    'Eventos': 'fas fa-calendar-alt',
    'Noticias': 'fas fa-newspaper',
    'Autenticação e Autorização': 'fas fa-lock',
    'Cadastros': 'fas fa-address-card',
    'Cadastro': 'fas fa-list',
    'UsuarioChat': 'fas fa-list',
    'App_Atividade': 'fas fa-tasks',  # Ajuste o ícone conforme necessário
    'Meu modelos': 'fas fa-cogs',  # Ajuste o ícone conforme necessário
}
